# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Contracts
description: Finds all registered contracts
full_batch_size: 100
# There's a bug in v3-alpha.5, which requires to have a global contract definition
contracts:
  - name: Noop
    events:
      - event: Noop()
chains:
  - id: 1
    start_block: 0
    hypersync_config:
      # Use traces to not handle different source block number
      url: https://1-traces.hypersync.xyz
